### ISSUE TITLE
Video component not updating correctly

### ISSUE THREAD

**Issue by lbucas** [hochschule-darmstadt/openartbrowser#141]
When viewing a video (e.g., Gothic), stopping it and navigating to another page with a video (e.g., Renaissance), then the last video is displayed (Gothic instead of Renaissance).

Refreshing the page will fix.

**Comment by jschurse** [comment]
Has been fixed on staging.

**Comment by lbucas** [comment]
I realized that the bug is not fixed entirely yet. When you switch from a page with a video to one with no video, the video component stays on the page without updating.

I will fix this.
